language: java
jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - docker run -d -p 3306:3306 --name mysql-docker-container -e MYSQL_ROOT_PASSWORD=admin -e MYSQL_DATABASE=hospital -e MYSQL_USER=admin -e MYSQL_PASSWORD=admin mysql:5.6